### ISSUE TITLE
Do the @ComponentScan on ApplicationContext#start

### ISSUE THREAD

**Issue by saskodh** [saskodh/framework#27]
## Background

Currently the component scanning is implemented in the decorator and it runs immediately when the configuration class is loaded. We would like to replace that with lazy loading that is done when the configuration class is used to start an ApplicationContext.
## Task

Make the @ComponentScan-ining lazy loading the components constructors on ApplicationContext startup. Make sure that other decorators used together with @ComponentScan work well with that. Example: @Import, @PropertySource..
Note: @PropertySource should also lazy load the properties file. (Pass the file path instead of the actual file).

**Comment by damjangelovski** [comment]
Fix TODOs for adding missing unit tests in ComponentScanUtil
